swagger: "2.0"
info:
  description: "Basic user authentication for random fact generator."
  version: "1.3.0"
  title: "User Authentication Final Round"
host: localhost:8080
basePath: "/accounts"
schemes:
- "https"
paths:
  /create:
    get:
      tags:
      - "Accounts"
      summary: "Creates an account for user"
      description: "Allows user to create an account for future logins"
      operationId: "create_account"
      produces:
      - "application/json"
      security:
      - basicAuth: []
      
      responses:
        200:
          description: "Created Account"
          schema:
            type: "integer"
            format: "int32"
        401:
          description: "Authentication header required"
          schema:
            type: "integer"
            format: "int32"    
        409:
          description: "Username already exists"
          schema:
            type: "integer"
            format: "int32"
        
  /login:
    put:
      tags:
      - "Accounts"
      summary: "Attempts to log a user in"
      description: "Given a username and password checks the database to see if those are the proper credentials to get access"
      operationId: "login_account"
      produces:
      - "application/json"
      security:
      - basicAuth: []
      responses:
        200:
          description: "Created Account"
          schema:
            type: "integer"
            format: "int32"
        401:
          description: "Authentication header required / Incorrect Username or Password"
          schema:
            type: "integer"
            format: "int32" 

securityDefinitions:
  basicAuth:
    type: basic

  
    
    